name: fans_spider_OB

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
  schedule:
    - cron: 20 3 * * *
  watch:
    types: started
  workflow_dispatch:
    inputs:
      fans_type:
        description: '涨粉榜？ (空down 1up)'
        required: false
        default: ''
      date_start:
        description: '开始时间 (如03 01 09)'
        required: true
        default: ''
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: pip依赖包
      run: |
        pip install -r requirements.txt
        
    - name: 抓取OB里的粉丝数据
#       判断types方式
      # if: github.event.action != 'started'
#       直接判断执行条件
      if: github.event_name == 'schedule'                   
      run: |
        python3 down_fans_biliob.py
        echo "============华丽的分割线==========="
        python3 up_fans_biliob.py
      
    - name: 获取指定数据
      if: github.event_name != 'schedule'
      env:
        date_start: ${{ github.event.inputs.date_start }}
        fans_type: ${{ github.event.inputs.fans_type }}
      run: |
        rm -rf temp/ && mkdir temp
        python3 get_fans.py
        tar -zcvf temp.tar.gz temp/
        
    - name: 上传
      run: |
        git config --local user.email "19820637553@163.com"
        git config --local user.name "XXXShaunPan"
        git add .
        git commit -m "`date '+%Y-%m-%d %H:%M:%S'`"
        git push -u origin main && echo "push ok"
        
    - name: 'Send mail'
      if: success()
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: "bili_fans_ob项目push成功通知"
        body: "OB涨掉粉榜爬取完成！"
        to: 630077372@qq.com
        from: OB_fans
        content_type: text/plain
